In [1]:
import numpy as np

In [3]:
list = [1,2,3,4,5,6,7,8,9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
 arr = np.array(list)

In [13]:
type(arr)

numpy.ndarray

In [18]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[0] + arr[5]

7

In [21]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
matriz[0,2]

3

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#Esta acción se le llama SLICING
arr[1:6]

array([2, 3, 4, 5, 6])

In [27]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [28]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[::3]

array([1, 4, 7])

In [30]:
arr[-1]

9

In [31]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [33]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])