In [1]:
import numpy as np

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [5]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [7]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [9]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


3

## Agregar o eliminar dimensiones

In [10]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [12]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [14]:
print(vector, vector.ndim)
vector2 = np.squeeze(vector)
print(vector2, vector2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
