In [1]:
import numpy as np

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
#Nos arroja una lista pero utilizando np.arange()
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#El 2 equivale al step; nos arroja los numeros multiplicados al mismo número del step
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#Nos permite definir estructuras previas x una estructura evaluada
#Utilizada más a nivel de data science
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
#Tiene los mismos propositos que zeros
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
#Creamos una distribución normalizada
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [17]:
#Es para algebra
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#Números aleatorios
np.random.rand()

0.4016134004308419

In [20]:
np.random.rand(4)

array([0.37823438, 0.07515821, 0.82667164, 0.41821009])

In [21]:
np.random.rand(4,4)

array([[0.87073382, 0.23200942, 0.0915898 , 0.4889757 ],
       [0.31733499, 0.33166978, 0.82817678, 0.83413987],
       [0.5973506 , 0.22954974, 0.85356853, 0.90972982],
       [0.57281008, 0.03965862, 0.20996412, 0.57380088]])

In [22]:
np.random.randint(1,15)

3

In [23]:
np.random.randint(1,100,(10,10))

array([[21, 55, 48, 62, 33, 12, 84, 84, 42, 10],
       [37,  1,  6, 61, 19, 62,  7, 46, 37, 10],
       [20, 87, 44, 46, 49, 16,  5, 36, 37, 28],
       [11, 64, 55, 48, 66,  9, 39, 48, 24,  9],
       [64, 78,  3, 63, 53, 14, 43, 34, 21, 57],
       [17, 50, 47, 73, 96, 69, 60, 83, 27, 71],
       [ 1, 42,  3, 13, 84,  3, 93, 62, 21, 10],
       [27, 28, 58, 91, 41, 24, 51,  6, 46, 35],
       [71, 83, 16, 64, 99, 45, 92, 85, 19, 55],
       [16, 68, 85, 27, 76, 66, 93, 23, 41, 13]])