In [1]:
import numpy as np

In [10]:
arrp = np.random.randint(1,10,(3,2))

In [11]:
#Nos arroja las filas y columnas que tengo. También si tengo dimensiones nos arroja las cantidades por dimensiones que se tiene
#Se le conoce como arreglo
arrp.shape

(3, 2)

In [12]:
arrp

array([[7, 2],
       [7, 8],
       [8, 7]])

In [13]:
#Reshape nos ordena los valores que tenemos adentro para que cumplan la condición dada.
arrp.reshape(1,6)

array([[7, 2, 7, 8, 8, 7]])

In [14]:
arr.reshape(2,3)

array([[2, 8, 1],
       [4, 8, 3]])

In [15]:
np.reshape(arrp,(1,6))

array([[7, 2, 7, 8, 8, 7]])

In [16]:
arrp

array([[7, 2],
       [7, 8],
       [8, 7]])

In [17]:
#Se define como tipo 'C'; lenguaje C
np.reshape(arrp,(2,3),'C')

array([[7, 2, 7],
       [8, 8, 7]])

In [18]:
#Se define como tipo 'F', lenguaje Fortran 'F'
np.reshape(arrp,(2,3),'F')

array([[7, 8, 8],
       [7, 2, 7]])

In [19]:
#Nos arroja a como esta optimizado con nuestro sistema
np.reshape(arrp,(2,3),'A')

array([[7, 2, 7],
       [8, 8, 7]])