In [1]:
import numpy as np

In [4]:
arrp = np.random.randint(1,20,10)

In [5]:
matriz = arrp.reshape(2,5)
matriz

array([[ 2,  8, 10,  6,  3],
       [ 6, 16, 19,  7,  6]])

In [7]:
arrp

array([ 2,  8, 10,  6,  3,  6, 16, 19,  7,  6])

In [8]:
arrp.max()

19

In [9]:
matriz.max()

19

In [12]:
matriz

array([[ 2,  8, 10,  6,  3],
       [ 6, 16, 19,  7,  6]])

In [14]:
matriz.max(1)

array([10, 19])

In [15]:
arrp.argmax()

7

In [17]:
#Aquí nos arroja el índice en donde se encuentra la cantidad más grande.
#Eg. Todos los números mayores están en el indíce 1
matriz.argmax(0)

array([1, 1, 1, 1, 1])

In [18]:
arrp.min()

2

In [19]:
matriz.min(0)

array([ 2,  8, 10,  6,  3])

In [22]:
matriz

array([[ 2,  8, 10,  6,  3],
       [ 6, 16, 19,  7,  6]])

In [24]:
matriz.argmin(0)

array([0, 0, 0, 0, 0])

In [25]:
arrp

array([ 2,  8, 10,  6,  3,  6, 16, 19,  7,  6])

In [26]:
#ptp = De un pico a otro pico, es decir, nos arroja la diferencia del valor más alto - el más pequeño.
#19 - 2 = 17
arrp.ptp()

17

In [28]:
matriz

array([[ 2,  8, 10,  6,  3],
       [ 6, 16, 19,  7,  6]])

In [27]:
matriz.ptp(0)

array([4, 8, 9, 1, 3])

In [46]:
#Nos permite arreglar los valores del min al max
arrp.sort()
arrp

array([ 2,  3,  6,  6,  6,  7,  8, 10, 16, 19])

FUNCIONES ESTADISTICAS

In [37]:
#Nos permite calcular el percentil
#Percentile = nos arroja el valor que tenemos en la mitad o 0 o 100
np.percentile(arrp,50)

6.5

In [39]:
np.median(arrp)

6.5

In [41]:
np.median(matriz,1)

array([ 6., 10.])

In [42]:
np.std(arrp)

5.119570294468081

In [44]:
np.std(arrp) ** 2

26.209999999999997

In [45]:
np.var(arrp)

26.21

In [47]:
np.mean(arrp)

8.3

In [49]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [50]:
np.concatenate((a,b),axis=0)

ValueError: ignored

In [65]:
a.ndim

2

In [72]:
b = np.expand_dims(b,axis=0)

In [73]:
#Se agregarón un chingo de dimensiones :V
b.ndim

6

In [67]:
np.concatenate((a,b),axis=0)

ValueError: ignored

In [57]:
np.concatenate((a,b),axis=1)

ValueError: ignored

In [58]:
#T = Es la transpuesta
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [60]:
b

array([[5, 6]])

In [61]:
b.T

array([[5],
       [6]])