In [ ]:
import numpy as np

In [ ]:
arrp = np.arange(0,11)
arrp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Esto es un slicing
trozo_arr = arrp[0:6]

In [ ]:
trozo_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Aquí quitamos todos los valores y los cambiamos a 0
trozo_arr[:] = 0
trozo_arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
arrp_copy = arrp.copy()

In [ ]:
arrp_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arrp_copy[:] = 100

In [ ]:
arrp_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arrp

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

NUEVO EJERCICIO

In [ ]:
datos = np.arange(0,21)
datos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
trozo_datos = datos[0:8]

In [ ]:
trozo_datos

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
datos_copy = datos.copy()

In [ ]:
datos_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])