In [1]:
import numpy as np

In [3]:
arrp = np.linspace(1,10,10, dtype='int8')
arrp

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [4]:
#Nos arroja una lista boolean
arrp > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
indic_cond = arrp > 5
indic_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
arrp[(indic_cond) & (arrp < 9)]

array([6, 7, 8], dtype=int8)

In [10]:
arrp[arrp > 5 ] = 99
arrp

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [11]:
arrp[arrp == 99]

array([99, 99, 99, 99, 99], dtype=int8)